"""Parameter and model recovery for uncertainty-aware official-pyhgf choices.

This uses complete reward schedules only to simulate counterfactual choices.
Candidate models see the reward generated by each simulated choice, exactly as
they would in an ordinary partial-feedback bandit trajectory.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

os.environ.setdefault("MPLCONFIGDIR", "/tmp/bayesd_misfits-matplotlib")

import jax
import jax.numpy as jnp
import numpy as np
from scipy.optimize import minimize

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bayesd_misfits.data import load_reward_schedules, reward_schedules_to_dataframe
from bayesd_misfits.pyhgf_bandit import NArmPyHGFUncertaintySticky


SEED = 20260808
N_TRAIN = int(os.environ.get("RECOVERY_N_TRAIN", 12))
N_VALID = int(os.environ.get("RECOVERY_N_VALID", 12))
N_STARTS = int(os.environ.get("RECOVERY_N_STARTS", 3))
OUTPUT_PATH = Path(
    os.environ.get(
        "RECOVERY_OUTPUT",
        "research/pyhgf_uncertainty_recovery_results.json",
    )
)

PARAM_ORDER = (
    "ghgf_omega",
    "beta",
    "uncertainty_weight",
    "repetition_weight",
)
BOUNDS = {
    "ghgf_omega": (-8.0, 0.0),
    "beta": (0.0, 15.0),
    "uncertainty_weight": (-10.0, 10.0),
    "repetition_weight": (-5.0, 5.0),
}
DEFAULTS = {
    "ghgf_omega": -4.0,
    "beta": 3.0,
    "uncertainty_weight": 0.0,
    "repetition_weight": 0.0,
}
CANDIDATES = {
    "value_only": ("ghgf_omega", "beta"),
    "uncertainty": ("ghgf_omega", "beta", "uncertainty_weight"),
    "uncertainty_repetition": PARAM_ORDER,
}
GENERATING_CASES = {
    "value_only": {
        "ghgf_omega": -3.0,
        "beta": 4.0,
        "uncertainty_weight": 0.0,
        "repetition_weight": 0.0,
    },
    "uncertainty_averse": {
        "ghgf_omega": -2.0,
        "beta": 3.0,
        "uncertainty_weight": -1.5,
        "repetition_weight": 0.0,
    },
    "diagnostic_like_combined": {
        "ghgf_omega": -1.0,
        "beta": 0.2,
        "uncertainty_weight": -0.9,
        "repetition_weight": 1.7,
    },
}


def load_complete_schedules() -> tuple[jnp.ndarray, jnp.ndarray]:
    """Return deterministic train/validation schedule arrays on the 0-1 scale."""
    frame = reward_schedules_to_dataframe(load_reward_schedules())
    complete_ids = frame.groupby("trajectory_id").size()
    complete_ids = np.asarray(sorted(complete_ids[complete_ids == 120].index))
    rng = np.random.default_rng(SEED)
    selected = rng.choice(
        complete_ids,
        size=N_TRAIN + N_VALID,
        replace=False,
    )
    matrices = []
    for trajectory_id in selected:
        trajectory = frame[frame["trajectory_id"] == trajectory_id].sort_values(
            "trial_id"
        )
        matrices.append(
            trajectory[["reward_0", "reward_1", "reward_2", "reward_3"]]
            .to_numpy(dtype=np.float32)
            / 100.0
        )
    schedules = jnp.asarray(np.stack(matrices))
    return schedules[:N_TRAIN], schedules[N_TRAIN:]


def parameter_dict(values: jnp.ndarray, active: tuple[str, ...]) -> dict[str, Any]:
    """Expand an active natural-scale vector to the combined learner parameters."""
    params = {name: jnp.asarray(DEFAULTS[name]) for name in PARAM_ORDER}
    for index, name in enumerate(active):
        params[name] = values[index]
    return params


def make_simulator(learner: NArmPyHGFUncertaintySticky):
    def simulate_one(key, schedule, parameter_values):
        params = parameter_dict(parameter_values, PARAM_ORDER)

        def trial(carry, available_rewards):
            state, trial_key = carry
            trial_key, choice_key = jax.random.split(trial_key)
            computed = learner.compute_jax(state, params, context={})
            logits = jnp.stack([computed[f"logit{i}"] for i in range(4)])
            choice = jax.random.categorical(choice_key, logits).astype(jnp.int32)
            feedback = available_rewards[choice]
            state = learner.update_jax(
                state,
                params,
                context={"choice": choice, "feedback": feedback},
            )
            return (state, trial_key), choice

        (_, _), choices = jax.lax.scan(
            trial,
            (learner.init_jax_state(), key),
            schedule,
        )
        return choices

    return jax.jit(jax.vmap(simulate_one, in_axes=(0, 0, None)))


def make_nll(learner: NArmPyHGFUncertaintySticky, active: tuple[str, ...]):
    def trajectory_logp(values, choices, schedule):
        params = parameter_dict(values, active)

        def trial(state, observation):
            choice, available_rewards = observation
            computed = learner.compute_jax(state, params, context={})
            logits = jnp.stack([computed[f"logit{i}"] for i in range(4)])
            logp = jax.nn.log_softmax(logits)[choice]
            feedback = available_rewards[choice]
            state = learner.update_jax(
                state,
                params,
                context={"choice": choice, "feedback": feedback},
            )
            return state, logp

        _, logps = jax.lax.scan(
            trial,
            learner.init_jax_state(),
            (choices, schedule),
        )
        return jnp.sum(logps)

    def total_nll(values, choices, schedules):
        return -jnp.sum(jax.vmap(trajectory_logp, in_axes=(None, 0, 0))(
            values, choices, schedules
        ))

    return jax.jit(jax.value_and_grad(total_nll)), jax.jit(total_nll)


def fit_candidate(
    learner: NArmPyHGFUncertaintySticky,
    name: str,
    choices: jnp.ndarray,
    train_schedules: jnp.ndarray,
    valid_choices: jnp.ndarray,
    valid_schedules: jnp.ndarray,
    rng: np.random.Generator,
) -> dict[str, Any]:
    active = CANDIDATES[name]
    value_and_grad, nll = make_nll(learner, active)
    bounds = [BOUNDS[param] for param in active]
    starts = [np.asarray([DEFAULTS[param] for param in active], dtype=float)]
    for _ in range(max(0, N_STARTS - 1)):
        starts.append(np.asarray([
            rng.uniform(lower, upper) for lower, upper in bounds
        ]))

    def objective(values):
        value, gradient = value_and_grad(
            jnp.asarray(values), choices, train_schedules
        )
        return float(value), np.asarray(gradient, dtype=float)

    fits = [
        minimize(
            objective,
            start,
            method="L-BFGS-B",
            jac=True,
            bounds=bounds,
            options={"maxiter": 250, "ftol": 1e-9},
        )
        for start in starts
    ]
    best = min(fits, key=lambda result: float(result.fun))
    train_nll = float(best.fun) / int(choices.size)
    valid_nll = float(
        nll(jnp.asarray(best.x), valid_choices, valid_schedules)
    ) / int(valid_choices.size)
    estimates = {param: float(best.x[index]) for index, param in enumerate(active)}
    n_observations = int(choices.size)
    bic = 2.0 * float(best.fun) + len(active) * np.log(n_observations)
    return {
        "success": bool(best.success),
        "message": str(best.message),
        "n_iterations": int(best.nit),
        "estimates": estimates,
        "train_nll": train_nll,
        "validation_nll": valid_nll,
        "bic": float(bic),
    }


def main() -> None:
    learner = NArmPyHGFUncertaintySticky()
    train_schedules, valid_schedules = load_complete_schedules()
    simulator = make_simulator(learner)
    rng = np.random.default_rng(SEED + 1)
    results: dict[str, Any] = {}

    for case_index, (case_name, generating) in enumerate(GENERATING_CASES.items()):
        values = jnp.asarray([generating[name] for name in PARAM_ORDER])
        train_keys = jax.random.split(
            jax.random.PRNGKey(SEED + case_index * 2), N_TRAIN
        )
        valid_keys = jax.random.split(
            jax.random.PRNGKey(SEED + case_index * 2 + 1), N_VALID
        )
        train_choices = simulator(train_keys, train_schedules, values)
        valid_choices = simulator(valid_keys, valid_schedules, values)
        print(f"\nRecovery case: {case_name}")
        candidate_results = {}
        for candidate in CANDIDATES:
            fit = fit_candidate(
                learner,
                candidate,
                train_choices,
                train_schedules,
                valid_choices,
                valid_schedules,
                rng,
            )
            candidate_results[candidate] = fit
            print(
                f"  {candidate:<24} valid NLL={fit['validation_nll']:.4f} "
                f"estimates={fit['estimates']}"
            )
        winner = min(
            candidate_results,
            key=lambda candidate: candidate_results[candidate]["validation_nll"],
        )
        results[case_name] = {
            "generating_parameters": generating,
            "validation_winner": winner,
            "candidates": candidate_results,
        }

    output = {
        "seed": SEED,
        "n_train_trajectories": N_TRAIN,
        "n_validation_trajectories": N_VALID,
        "n_trials": 120,
        "n_optimization_starts": N_STARTS,
        "method": "population maximum likelihood with L-BFGS-B",
        "uses_full_schedules": "simulation only; candidate updates are chosen-feedback only",
        "results": results,
    }
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w", encoding="utf-8") as file:
        json.dump(output, file, indent=2, allow_nan=False)
    print(f"\nSaved recovery results to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
