"""Bayes'd Misfits — MindRL Challenge 2026."""

from bayesd_misfits.data import (
    ensure_data_downloaded,
    load_challenge_data,
    load_trajectories,
    load_reward_schedules,
    trajectories_to_dataframe,
    reward_schedules_to_dataframe,
    summarize_data,
    validate_for_hssm,
)
from bayesd_misfits.model import NArmRescorlaWagner, NArmRWDriftLearner, NArmDualAlphaRW, NArmRWSticky, NArmRWDualAlphaSticky
from bayesd_misfits.causal_rw import (
    NArmCausalScaleDualAlphaChoiceTrace,
    NArmCausalScaleDualAlphaNoHistory,
    NArmCausalScaleDualAlphaSticky,
    NArmCausalScaleSingleAlphaChoiceTrace,
    NArmCausalScaleSingleAlphaNoHistory,
    NArmCausalScaleSingleAlphaSticky,
)
from bayesd_misfits.hgf import NArmHGF, NArmHGFDriftLearner, NArmHGFSticky
from bayesd_misfits.bms import (
    CHAIN_FREQ,
    COMMON_CAUSE_FREQ,
    COMMON_EFFECT_FREQ,
    FIGURE2_QUERIES,
    bits_to_state,
    ms_response_category,
    mutation_chain,
    mutation_chains_jax,
    neighbors,
    normative_response,
    normalize_joint,
    response_from_chain,
    simulate_responses,
    state_to_bits,
    table1_breakdown,
)
from bayesd_misfits.causal_sampling_bandit import (
    CausalSamplingBandit,
    CausalSamplingBanditTrace,
    NArmCausalSamplingBandit,
    NArmCausalSamplingBanditTrace,
)
from bayesd_misfits.pyhgf_bandit import (
    ContinuousGHGFConfig,
    GHGFReplay,
    NArmPyHGF,
    NArmPyHGFSticky,
    NArmPyHGFUncertainty,
    NArmPyHGFUncertaintySticky,
    OnlineContinuousGHGF,
    build_continuous_ghgf,
    replay_continuous_ghgf,
)

__all__ = [
    "ensure_data_downloaded",
    "load_challenge_data",
    "load_trajectories",
    "load_reward_schedules",
    "trajectories_to_dataframe",
    "reward_schedules_to_dataframe",
    "summarize_data",
    "CausalSamplingBandit",
    "CausalSamplingBanditTrace",
    "NArmCausalSamplingBandit",
    "NArmCausalSamplingBanditTrace",
    "validate_for_hssm",
    "NArmRescorlaWagner",
    "NArmRWDriftLearner",
    "NArmDualAlphaRW",
    "NArmRWSticky",
    "NArmRWDualAlphaSticky",
    "NArmCausalScaleDualAlphaSticky",
    "NArmCausalScaleDualAlphaNoHistory",
    "NArmCausalScaleDualAlphaChoiceTrace",
    "NArmCausalScaleSingleAlphaSticky",
    "NArmCausalScaleSingleAlphaNoHistory",
    "NArmCausalScaleSingleAlphaChoiceTrace",
    "NArmHGF",
    "NArmHGFSticky",
    "NArmHGFDriftLearner",
    "CHAIN_FREQ",
    "COMMON_CAUSE_FREQ",
    "COMMON_EFFECT_FREQ",
    "FIGURE2_QUERIES",
    "bits_to_state",
    "ms_response_category",
    "mutation_chain",
    "mutation_chains_jax",
    "neighbors",
    "normative_response",
    "normalize_joint",
    "response_from_chain",
    "simulate_responses",
    "state_to_bits",
    "table1_breakdown",
    "CausalSamplingBandit",
    "NArmCausalSamplingBandit",
    "ContinuousGHGFConfig",
    "GHGFReplay",
    "NArmPyHGF",
    "NArmPyHGFSticky",
    "NArmPyHGFUncertainty",
    "NArmPyHGFUncertaintySticky",
    "OnlineContinuousGHGF",
    "build_continuous_ghgf",
    "replay_continuous_ghgf",
]
